#! /bin/sh

# Make a single file that can be used with dofile

cat <<EOF
function require (f)
  package.loaded[f] = true
end
EOF

# FIXME: This list should be generated automatically from inspection
# of the sources, by grepping for "^require" and following the
# dependency tree, starting at std.lua.

cat \
  std/base.lua \
  std/debug.lua \
  std/table.lua \
  std/list.lua \
  std/object.lua \
  std/lcs.lua \
  std/string.lua \
  std/xml.lua \
  std/rex.lua \
  std/math.lua \
  std/bit.lua \
  std/io.lua \
  std/file.lua \
  std/getopt.lua \
  std/set.lua \
  std/parser.lua \
  std/mbox.lua \
  std.lua # comes last to lift modules into global environment
